### ISSUE TITLE
Can't Convert DmUser to Array

### ISSUE THREAD

**Issue by aleksclark** [maxjustus/sinatra-authentication#23]
Same issue as posted by another user, datamapper associations don't seem to be functional.

Here's some code that illustrates the problem:

https://gist.github.com/1157210

**Comment by namelessjon** [comment]
This is caused by the method_missing method defined on the DmUser which causes some methods in dm-core to blow up.  There are a couple of possible work arounds.  One is to define an explicit `#to_ary` method

``` ruby
class DmUser
  # stuff here
  def to_ary
    [self]
  end
end
```

The other is to make the `method_missing` less promiscuous, something like

``` ruby
def method_missing(m, *args)
  if m.to_s =~ /\?$/
    return false
  else
    super
  end
end
```

so it would return false for `#authorised?` or `#special_user?` but give `NoMethodError` for `#stuff` or `#to_ary`
