### ISSUE TITLE
Overriding template engine not possible

### ISSUE THREAD

**Issue by simonszu** [maxjustus/sinatra-authentication#55]
Hi,

i have designed my sinatra app as a standalone-app and not as a subclass of Sinatra::Application.
However, the setting for overriding the template engine from haml to erb is not working for me. 
I have made the setting

```
configure do
   set :template_engine, :erb
end
```

and still get the following error: 

> LoadError at /login
> cannot load such file -- haml

**Comment by scouttyg** [comment]
I had the same problem, and had to pull straight from the git repo in order to fix it, as I believe its fixed in 0.4.2, but rubygems is still on 0.4.1 [(probably because there are still references to 0.4.1 in the code)](https://github.com/scouttyg/sinatra-authentication/blob/master/Rakefile#L10)

Try this instead:

`gem 'sinatra-authentication', :git => 'git://github.com/maxjustus/sinatra-authentication.git'`

You'll also need to provide the erb files, since they aren't included in the gem. So that means you'll probably have to add this line as well:

`set :sinatra_authentication_view_path, Pathname(__FILE__).dirname.expand_path + "my_views/"`

Where "my_views" is the folder where you're views are located in the root directory of the app.
